/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as StudentsRouteImport } from './routes/students'
import { Route as SignupEmailRouteImport } from './routes/signup-email'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PtHistoryRouteImport } from './routes/pt-history'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoTrainerRouteImport } from './routes/demo.trainer'
import { Route as DemoStudentRouteImport } from './routes/demo.student'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AccountDeleteRouteImport } from './routes/account.delete'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupEmailRoute = SignupEmailRouteImport.update({
  id: '/signup-email',
  path: '/signup-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PtHistoryRoute = PtHistoryRouteImport.update({
  id: '/pt-history',
  path: '/pt-history',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTrainerRoute = DemoTrainerRouteImport.update({
  id: '/demo/trainer',
  path: '/demo/trainer',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStudentRoute = DemoStudentRouteImport.update({
  id: '/demo/student',
  path: '/demo/student',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountDeleteRoute = AccountDeleteRouteImport.update({
  id: '/account/delete',
  path: '/account/delete',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/booking': typeof BookingRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/pt-history': typeof PtHistoryRoute
  '/reset-password': typeof ResetPasswordRoute
  '/schedule': typeof ScheduleRoute
  '/signup-email': typeof SignupEmailRoute
  '/students': typeof StudentsRoute
  '/team': typeof TeamRoute
  '/account/delete': typeof AccountDeleteRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/demo/student': typeof DemoStudentRoute
  '/demo/trainer': typeof DemoTrainerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/booking': typeof BookingRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/pt-history': typeof PtHistoryRoute
  '/reset-password': typeof ResetPasswordRoute
  '/schedule': typeof ScheduleRoute
  '/signup-email': typeof SignupEmailRoute
  '/students': typeof StudentsRoute
  '/team': typeof TeamRoute
  '/account/delete': typeof AccountDeleteRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/demo/student': typeof DemoStudentRoute
  '/demo/trainer': typeof DemoTrainerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/booking': typeof BookingRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/pt-history': typeof PtHistoryRoute
  '/reset-password': typeof ResetPasswordRoute
  '/schedule': typeof ScheduleRoute
  '/signup-email': typeof SignupEmailRoute
  '/students': typeof StudentsRoute
  '/team': typeof TeamRoute
  '/account/delete': typeof AccountDeleteRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/demo/student': typeof DemoStudentRoute
  '/demo/trainer': typeof DemoTrainerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/booking'
    | '/checkout'
    | '/login'
    | '/pricing'
    | '/profile'
    | '/pt-history'
    | '/reset-password'
    | '/schedule'
    | '/signup-email'
    | '/students'
    | '/team'
    | '/account/delete'
    | '/auth/callback'
    | '/demo/student'
    | '/demo/trainer'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/booking'
    | '/checkout'
    | '/login'
    | '/pricing'
    | '/profile'
    | '/pt-history'
    | '/reset-password'
    | '/schedule'
    | '/signup-email'
    | '/students'
    | '/team'
    | '/account/delete'
    | '/auth/callback'
    | '/demo/student'
    | '/demo/trainer'
  id:
    | '__root__'
    | '/'
    | '/booking'
    | '/checkout'
    | '/login'
    | '/pricing'
    | '/profile'
    | '/pt-history'
    | '/reset-password'
    | '/schedule'
    | '/signup-email'
    | '/students'
    | '/team'
    | '/account/delete'
    | '/auth/callback'
    | '/demo/student'
    | '/demo/trainer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookingRoute: typeof BookingRoute
  CheckoutRoute: typeof CheckoutRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  ProfileRoute: typeof ProfileRoute
  PtHistoryRoute: typeof PtHistoryRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ScheduleRoute: typeof ScheduleRoute
  SignupEmailRoute: typeof SignupEmailRoute
  StudentsRoute: typeof StudentsRoute
  TeamRoute: typeof TeamRoute
  AccountDeleteRoute: typeof AccountDeleteRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  DemoStudentRoute: typeof DemoStudentRoute
  DemoTrainerRoute: typeof DemoTrainerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup-email': {
      id: '/signup-email'
      path: '/signup-email'
      fullPath: '/signup-email'
      preLoaderRoute: typeof SignupEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pt-history': {
      id: '/pt-history'
      path: '/pt-history'
      fullPath: '/pt-history'
      preLoaderRoute: typeof PtHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/trainer': {
      id: '/demo/trainer'
      path: '/demo/trainer'
      fullPath: '/demo/trainer'
      preLoaderRoute: typeof DemoTrainerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/student': {
      id: '/demo/student'
      path: '/demo/student'
      fullPath: '/demo/student'
      preLoaderRoute: typeof DemoStudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/delete': {
      id: '/account/delete'
      path: '/account/delete'
      fullPath: '/account/delete'
      preLoaderRoute: typeof AccountDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookingRoute: BookingRoute,
  CheckoutRoute: CheckoutRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  ProfileRoute: ProfileRoute,
  PtHistoryRoute: PtHistoryRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ScheduleRoute: ScheduleRoute,
  SignupEmailRoute: SignupEmailRoute,
  StudentsRoute: StudentsRoute,
  TeamRoute: TeamRoute,
  AccountDeleteRoute: AccountDeleteRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  DemoStudentRoute: DemoStudentRoute,
  DemoTrainerRoute: DemoTrainerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
