/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as StudentsRouteImport } from './routes/students'
import { Route as SignupEmailRouteImport } from './routes/signup-email'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as PtHistoryRouteImport } from './routes/pt-history'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as IndexRouteImport } from './routes/index'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupEmailRoute = SignupEmailRouteImport.update({
  id: '/signup-email',
  path: '/signup-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const PtHistoryRoute = PtHistoryRouteImport.update({
  id: '/pt-history',
  path: '/pt-history',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/booking': typeof BookingRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/pt-history': typeof PtHistoryRoute
  '/schedule': typeof ScheduleRoute
  '/signup-email': typeof SignupEmailRoute
  '/students': typeof StudentsRoute
  '/team': typeof TeamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/booking': typeof BookingRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/pt-history': typeof PtHistoryRoute
  '/schedule': typeof ScheduleRoute
  '/signup-email': typeof SignupEmailRoute
  '/students': typeof StudentsRoute
  '/team': typeof TeamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/booking': typeof BookingRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/pt-history': typeof PtHistoryRoute
  '/schedule': typeof ScheduleRoute
  '/signup-email': typeof SignupEmailRoute
  '/students': typeof StudentsRoute
  '/team': typeof TeamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/booking'
    | '/login'
    | '/pricing'
    | '/profile'
    | '/pt-history'
    | '/schedule'
    | '/signup-email'
    | '/students'
    | '/team'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/booking'
    | '/login'
    | '/pricing'
    | '/profile'
    | '/pt-history'
    | '/schedule'
    | '/signup-email'
    | '/students'
    | '/team'
  id:
    | '__root__'
    | '/'
    | '/booking'
    | '/login'
    | '/pricing'
    | '/profile'
    | '/pt-history'
    | '/schedule'
    | '/signup-email'
    | '/students'
    | '/team'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookingRoute: typeof BookingRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  ProfileRoute: typeof ProfileRoute
  PtHistoryRoute: typeof PtHistoryRoute
  ScheduleRoute: typeof ScheduleRoute
  SignupEmailRoute: typeof SignupEmailRoute
  StudentsRoute: typeof StudentsRoute
  TeamRoute: typeof TeamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup-email': {
      id: '/signup-email'
      path: '/signup-email'
      fullPath: '/signup-email'
      preLoaderRoute: typeof SignupEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pt-history': {
      id: '/pt-history'
      path: '/pt-history'
      fullPath: '/pt-history'
      preLoaderRoute: typeof PtHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookingRoute: BookingRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  ProfileRoute: ProfileRoute,
  PtHistoryRoute: PtHistoryRoute,
  ScheduleRoute: ScheduleRoute,
  SignupEmailRoute: SignupEmailRoute,
  StudentsRoute: StudentsRoute,
  TeamRoute: TeamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
